### ISSUE TITLE
Error while trying to access to admin console when logged user has only manage-users and view-users roles

### ISSUE THREAD

**Issue by wrinkle81** [keycloak/keycloak-community#249]
Server Version: 12.0.4

I have create new realm, that contains a new user X.
The X user has mapped following client roles
- realm-management\manage-users
- realm-management\view-users

When I try to access to console by its address http://192.168.60.20:8080/auth/admin/MySqlSpringBootDemo/console/#
(where MySqlSpringBootDemo is my realm). I'm redirected to error page "Forbidden You don't have access to the requested resource."

After some investigation in network monitor, I notice that the only request that fails with 403 error is

http://192.168.60.20:8080/auth/admin/realms/MySqlSpringBootDemo/localization/it

I also try to change locale without success.

I get success to access adding to my user X the role
- realm-management\view-realm

The error disappear but the user now, as expected, has access to indesidered info

**Comment by cukal** [comment]
I'm having the same issue on 12.0.3. 
User has: 

manage-users
query-groups
query-users

When opening the realm admin console as that user the page shows: 

```
Resource not found...
We could not find the resource you are looking for. Please make sure the URL you entered is correct.

Go to the home page »
```

It seems to happen when ```/auth/resources/8io7g/admin/keycloak/partials/menu.html``` is requested, the next URL after that is the ```/auth/admin/dpp_dev_dpp_dileoz_network/console/#/notfound``` URL.

Clicking on "Go to the home page" returns the users to the correct admin page where only user / group info is seen.

**Comment by dagb** [comment]
> The admin console seems to be set to default open "Realm Settings".
> If the users does not have a role that includes it, the error is thrown, the user must click on "go to home page" and then the correct homepage (with only options the user has rights to) is shown.

That is a good observation I think. But is there any workaround?

**Comment by stakx** [comment]
> After some investigation in network monitor, I notice that the only request that fails with 403 error is
>
> http://192.168.60.20:8080/auth/admin/realms/MySqlSpringBootDemo/localization/it
>
> [...] I get success to access adding to my user X the role
>
> * realm-management\view-realm

@leischt @danielFesenmeyer, was this possibly caused by https://github.com/keycloak/keycloak/commit/e131de9574d018f4cb19d785131fcc608137d7b7 (e.g. [`requireViewRealm` in these lines of code](https://github.com/keycloak/keycloak/commit/e131de9574d018f4cb19d785131fcc608137d7b7#diff-b06765d78b9f04fe7ace1aad6dc18c74466052e419d2692a5b7f3a27423954acR148-R156))? I'm wondering what the thinking was behind requiring `viewRealm` permissions just for localization texts?

**Comment by leischt** [comment]
Hi, the permission check was Introduced, as the localization text is a sub-resource of the realm.
Nevertheless the admin UI should be usable even without the permissions view-realm.
There is already a Bug ticket for this issue: https://issues.redhat.com/browse/KEYCLOAK-17387

We will have a look into this.

**Comment by klose4711** [comment]
We have the same issue with 12.0.4

**Comment by m4rc77** [comment]
We did also hit this issue with Keycloak 12.0.3. Today i started Docker container `jboss/keycloak:13.0.0` for testing and it looks as this issue is gone. Maybe the fixing of https://issues.redhat.com/browse/KEYCLOAK-17387 in Keycloak 13 solved this issue too.

**Could anyone else, confirm, that this issue no longer exists with Keycloak `13.0.0`?**

**Comment by zechmeister** [comment]
@m4rc77 I can confirm, that `13.0.0` solved the issue. 

I guess, it's thank to https://github.com/keycloak/keycloak/pull/7940

**Comment by stianst** [comment]
This is not the correct place to report bugs or ask for help. Please see https://www.keycloak.org/community for more information.
